### ISSUE TITLE
Team Meeting #2

### ISSUE THREAD

**Issue by lgainsbrook** [chingu-voyage4/Toucans-Team-14#5]
Waffle.io 
- everyone on? 
- Walk through the system/organization options (waffle, GitHub wiki, Google Docs) for sharing docs, planning meetings, etc. (not issues)
-- choose one system

Project Details/Outline
- layers/star reaches look good? 
- Anything missing or need to be moved?
GitHub
- cloned, know how to fetch & merge (pull), stage, commit, push
- commit messages (present tense)
- Questions about how it works?

Set and assign tasks for first sprint (layer 2)

**Comment by stufinn** [comment]
From Wizard Milestone 1:
•  Determine at least one primary technical learning goal for each teammate
•  Pick something that is 25% outside of the team''s comfort zone / skillset. Any further and you will likely be overwhelmed. Any less and you are limiting your rate of learning.

- group screenshot! :)
