### ISSUE TITLE
Coding Guidelines

### ISSUE THREAD

**Issue by lgainsbrook** [chingu-voyage4/Toucans-Team-14#6]
Coding Guidelines
starting point for developing our own guidelines: https://github.com/ollyjohn/turtles-nineteen/wiki/Code-standards
Four branch-naming options:
- bug/name
- feature/name
- refactor/name
- style/name

Commenting:
- all caps, wrapped in ***

**Comment by stufinn** [comment]
Would an example name be:  style/stu ? Would you indicate in the branch name what the change actually is? ie. background_color?
